spring.application.name=jdbcPrac
# HSQLDB File-Based Connection
spring.datasource.url=jdbc:hsqldb:file:./data/demodb;shutdown=true
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=SA
spring.datasource.password=

# Tell Spring to initialize the database using our SQL files
spring.sql.init.mode=always
# Optional: This ensures the table is cleared before data.sql runs to avoid primary key errors
spring.sql.init.continue-on-error=true

spring.h2.console.enabled=true
# This allows you to access the console from your browser
spring.h2.console.path=/h2-console


